'use client';

import React, { useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { HelpCircle, Sparkles, Plus, BookOpen, Clock, Award } from 'lucide-react';
import { useAuth } from '../../hooks/useAuth';
import LoadingState from '../../components/common/LoadingState';

export default function QuizPage() {
  const router = useRouter();
  const { isAuthenticated, isLoading } = useAuth();

  useEffect(() => {
    if (!isLoading && !isAuthenticated) {
      router.push('/login');
    }
  }, [isLoading, isAuthenticated, router]);

  if (isLoading) {
    return <LoadingState message="Loading quiz modules..." />;
  }

  if (!isAuthenticated) return null;

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 border border-blue-100 text-blue-700 text-xs font-semibold mb-2">
            <Sparkles className="w-3.5 h-3.5" />
            <span>AI Module Placeholder</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight">
            Adaptive Quizzes
          </h1>
          <p className="text-sm text-slate-500 mt-1">
            Dynamic assessments generated by AI to evaluate your conceptual depth.
          </p>
        </div>

        <button
          disabled
          className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-slate-200 text-slate-500 text-sm font-semibold cursor-not-allowed self-start sm:self-auto"
        >
          <Plus className="w-4 h-4" />
          <span>Generate New Quiz</span>
        </button>
      </div>

      {/* Available Subjects for Quiz */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { name: 'DBMS', code: 'CS301', desc: 'Relational model, SQL, Normalization', quizzes: 8 },
          { name: 'Computer Networks', code: 'CS302', desc: 'OSI layers, TCP/IP, Congestion', quizzes: 6 },
          { name: 'NLP', code: 'AI401', desc: 'Embeddings, TF-IDF, Transformers', quizzes: 5 },
          { name: 'Java', code: 'CS202', desc: 'OOP, Collections, Multithreading', quizzes: 5 },
        ].map((subject) => (
          <div
            key={subject.code}
            className="bg-white rounded-2xl p-5 border border-slate-200/80 shadow-xs flex flex-col justify-between"
          >
            <div>
              <span className="text-xs font-bold text-blue-600 uppercase tracking-wider">
                {subject.code}
              </span>
              <h3 className="text-base font-bold text-slate-900 mt-1">{subject.name}</h3>
              <p className="text-xs text-slate-500 mt-1 leading-relaxed">{subject.desc}</p>
            </div>
            <div className="mt-4 pt-3 border-t border-slate-100 flex items-center justify-between text-xs text-slate-400">
              <span>{subject.quizzes} past quizzes</span>
              <span className="text-blue-600 font-semibold">Phase 2</span>
            </div>
          </div>
        ))}
      </div>

      {/* Placeholder Announcement */}
      <div className="rounded-3xl bg-white p-8 sm:p-12 border border-slate-200/80 shadow-xs text-center">
        <div className="w-14 h-14 rounded-2xl bg-indigo-50 text-indigo-600 flex items-center justify-center mx-auto mb-4">
          <HelpCircle className="w-7 h-7" />
        </div>
        <h3 className="text-xl font-bold text-slate-900">AI Quiz Engine In Development</h3>
        <p className="text-sm text-slate-500 max-w-md mx-auto mt-2 leading-relaxed">
          The quiz foundation, models, and controllers are prepared. Rihan&apos;s AI service will
          generate multiple-choice and conceptual assessment questions in Phase 2.
        </p>
      </div>
    </div>
  );
}